<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UG4A5PN" failures="0" tests="5" name="lws.selenium.testcases.LoginTest1" time="85.456" errors="1" timestamp="2023-02-09T16:00:46 IST" skipped="0">
  <testcase classname="lws.selenium.testcases.LoginTest1" name="TC001_LoginValidcase" time="31.113">
    <error message="Exception in com.lws.action.UIActions.tapUsingLocatorType()" type="com.lws.exceptions.AutomationException">
      <![CDATA[com.lws.exceptions.AutomationException: Exception in com.lws.action.UIActions.tapUsingLocatorType()
at com.lws.action.UIActions.tapUsingLocatorType(UIActions.java:105)
at lws.selenium.testcases.LoginTest1.TC001_LoginValidcase(LoginTest1.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.lws.exceptions.AutomationException: Unable to locate 'By.xpath: //div[@class='menu-item ']'
at com.lws.action.UtilityActions.getWebElement(UtilityActions.java:73)
at com.lws.action.UIActions.tapUsingLocatorType(UIActions.java:97)
... 29 more
]]>
    </error>
  </testcase> <!-- TC001_LoginValidcase -->
  <system-out/>
  <testcase classname="lws.selenium.testcases.LoginTest1" name="TC002_LoginInvalidcase" time="19.464"/>
  <system-out/>
  <testcase classname="lws.selenium.testcases.LoginTest1" name="TC003_LoginInvalidcase" time="9.995"/>
  <system-out/>
  <testcase classname="lws.selenium.testcases.LoginTest1" name="TC004_LoginInvalidcase" time="8.460"/>
  <system-out/>
  <testcase classname="lws.selenium.testcases.LoginTest1" name="TC005_LoginInvalidcase" time="16.424"/>
  <system-out/>
</testsuite> <!-- lws.selenium.testcases.LoginTest1 -->
